### ISSUE TITLE
how about .p files

### ISSUE THREAD

**Issue by over-star** [MrGranddy/EfficientSeg#2]
thank you for your work. I have a question. I see .p files,how to use it?

**Comment by MrGranddy** [comment]
Hello, your welcome. The ".p" files are also in the original baseline repo (https://github.com/VIPriors/vipriors-challenges-toolkit/tree/master/semantic-segmentation/helpers) of the challenge. The dataset we use is a small subset of Cityscapes dataset, the ".p" files are probably storing the selected subset names of train, val, set images.
